### ISSUE TITLE
Failed to load ZombieSharp.dll due to invalid function pointer

### ISSUE THREAD

**Issue by Slush1998** [oylsister/ZombieSharp#52]
09:12:20 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/ZombieSharp/ZombieSharp.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
   at ZombieSharp.ZombieSharp.VirtualFunctionsInitialize() in E:\Github\ZombieSharp\ZombieSharp\VirtualFunctions.cs:line 38
   at ZombieSharp.ZombieSharp.Load(Boolean HotReload) in E:\Github\ZombieSharp\ZombieSharp\ZombieSharp.cs:line 49
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

the plugin runs fine, they only thing that is game breaking is that zombies can carry weapons. im stuck with this problem can someone pls help a dummy?

**Comment by oylsister** [comment]
Os and CSS version?

**Comment by Slush1998** [comment]
Im pretty sure its CSS Version

**Comment by oylsister** [comment]
yes I asked what is your css version and what server os you running on.

**Comment by Slush1998** [comment]
sorry im dumb at this, but if you mean sharp version its v284, im not sure what you mean of "os" im very sorry and glad that you trying to help anyways that means alot

**Comment by Slush1998** [comment]
but i know its linux if it helps?

**Comment by Slush1998** [comment]
For me it seems like you fixed all my problems with this, how do i change to this? Updated API and Virtual Function #51

**Comment by oylsister** [comment]
It seem that lastest cs2 update broke the signature.

**Comment by oylsister** [comment]
nvm go to gamedata.json and edit signature to this
```json
"CCSPlayer_ItemServices_CanAcquire": {
    "signatures": {
      "library": "server",
      "windows": "48 8B C4 44 89 40 ? 48 89 50 ? 48 89 48",
      "linux": "55 48 89 E5 41 57 41 56 48 8D 45 ? 41 55 41 54 53 48 89 CB"
    }
}
```

**Comment by Slush1998** [comment]
That worked, thank you so much

**Comment by Slush1998** [comment]
Hello again, i can play now, i just wonna ask if you know anyhing about this error i now get? Im im already so glad for they fix you already helped with.

09:15:37 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'CounterStrikeSharp.API.Core.CCSPlayerController' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ZombieSharp.ZombieSharp.ZombieVoiceOnClientDisconnect(CCSPlayerController controller) in E:\Github\ZombieSharp\ZombieSharp\ZombieVoice.cs:line 16
   at ZombieSharp.ZombieSharp.OnClientDisconnected(Int32 client) in E:\Github\ZombieSharp\ZombieSharp\EventModule.cs:line 128
   at InvokeStub_OnClientDisconnect.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass51_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 298
   at InvokeStub_Action`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context)

**Comment by oylsister** [comment]
You can ignore that error, but I will have extra check for it.
